### PR TITLE
stk issue 87: Updated demo project to VS2017.

### PR DESCRIPTION
**Pull request by cepthomas**
Removed old project build files. Updated doc.

### CODE REVIEW

**Comment by radarsat1** [comment]
@garyscavone I'll try to verify this before merging it, but in principle are you okay with removing the old VS project files?  (VS2017 is a free download so it's less urgent to support old versions than it used to be..)

**Comment by cepthomas** [comment]
FYI I deliberated then removed them from the demo project because: a) they
are unusable now, b) if the user tries to open them there is a chance to
overwrite the new project files locally.

Chris

**Comment by cepthomas** [comment]
Further complicating things, I have found reference to building using VS6 in other places:
- stk\doc\doxygen\compile.txt
- stk\doc\doxygen\faq.txt
- stk\doc\doxygen\usage.txt
- stk\doc\README-Win.txt

I guess the owners should decide whether or not to support VS and if so, update all projects and docs, and if not, remove all traces. Or just leave sleeping dogs lie because apparently there aren't too many peeps trying to wake them up anyways, in which case you can just reject this PR. I'll continue my OSC work using VS2017 (maybe Qt too?) and if someone has interest in win dev they can be pointed in that direction.

**Comment by garyscavone** [comment]
If the current VS files are no longer functional (they are no longer automatically updated when opened in newer versions of VS), then I am in favour of having them updated. However, they should _all_ be updated, not just a few of them. I looked through the documentation pages in the list below but found nothing mentioning VS in the faq.txt file. Otherwise, the other documentation references can easily be updated.

Just to be clear, one of the main points in developing STK (more than 20 years ago) was to minimize OS / compiler issues by writing generic C++ code and avoiding GUI code as much as possible.

**Comment by cepthomas** [comment]
Since I started this, I'll go ahead and update all the projects and docs appropriately.

No guis involved....

**Comment by cepthomas** [comment]
I'm done (I think), please have a look. There could be more polishing of the docs but that would require cross-platform input. I also added a Visual Studio template that should make it easier for users to create new ones.

**Comment by radarsat1** [comment]
Hi, I tested this with Visual Studio 2017, it definitely failed to import the old project and now works, so thanks very much for this contribution.  The only fix I made was to rename demo.exe to stk-demo.exe to correspond with the launch scripts.  But I can confirm that compiling with this project and running StkDemo.bat worked beautifully out of the box.  (I installed tcl/tk through MSYS2.)

**Comment by cepthomas** [comment]
Thanks for reviewing and catching the output file name error.

Chris

**Pull request merged**
