### PR TITLE
Makefile: demo project needs realtime

### PR DESCRIPTION
**Pull request by fsateler**
So do not build it when not available

### CODE REVIEW

**Comment by garyscavone** [comment]
The demo project should be compilable without realtime support.  It could be run with scorefile input and output could be written to an audio file.  Perhaps something has changed in the code such that it doesn't compile correctly without the realtime flag, but if that is the case, the program needs to be fixed.

**Comment by fsateler** [comment]
gah. Sorry for the noise. The problem is that rtaudio fails to build on non-linux debian archs when using the autotools build: https://github.com/thestk/rtaudio/blob/master/configure.ac#L230 , and the demo project needs rtaudio.

I'll fix that problem in debian instead.

**Comment by radarsat1** [comment]
What is non-linux debian, and what steps can projects take to support it?

**Comment by fsateler** [comment]
Debian has ports not only for different architectures, but it also has ports that swap out the linux kernel for another. [Ports exist for kfreebsd and hurd](https://www.debian.org/ports/)

Most software should not really care. This looks sufficiently like a linux system that it should mostly work (except linux-specific interfaces like ALSA will not be available). I think the rtaudio configure script tries to be more clever than is necessary. Instead of guessing by OS which parameters to support (in this case, it did not consider the freebsd or hurd variants), it should always offer them, and just fail if there are none available.

**Pull request closed without merging**
