### PR TITLE
Fixed missing include and define for FreeBSD.

### PR DESCRIPTION
**Pull request by yurivict**

### CODE REVIEW

**Comment by garyscavone** [comment]
I can merge this but I typically import the latest version of RtAudio from the "thestk/rtaudio" github repo before making a new release. Can you submit a similar PR directly to the rtaudio repo?

**Comment by yurivict** [comment]
> I typically import the latest version of RtAudio from the "thestk/rtaudio" github repo 

Why do you need to import?
git modules are for this. They allow to attach one repository to another.

**Comment by garyscavone** [comment]
Perhaps things have changed, but when we were setting up the github repos some X years ago, the current structure was the best option. In general, I want RtMidi and RtAudio to be separate repos because there are many developers that are interested in those but not in the rest of STK. 
At the same time, I want to keep the download of STK as a single bundle and the compilation process relatively simple. The only part of RtMidi and RtAudio we really want in STK are the two header and .cpp files, not all the test programs and miscellaneous configuration scripts / files.

For me, it is easier to simply copy the files before a new release but if someone wants to investigate how to integrate RtMidi and RtAudio as submodules into STK, I'm open to that.

**Comment by yurivict** [comment]
Ok! Could you just commit the change that I submitted into the right repo?

**Comment by radarsat1** [comment]
I don't understand this patch.  sys/soundcard.h is included if you select OSS.

As for AFMT_FLOAT, I assume if it doesn't exist then it is not supported.  Wouldn't the following be a better change?
```C++
#ifdef AFMT_FLOAT                                                                        
  if ( mask & AFMT_FLOAT )                                                               
    info.nativeFormats |= RTAUDIO_FLOAT32;                                               
#endif     
```

**Comment by radarsat1** [comment]
I applied my modification to your PR in https://github.com/thestk/rtaudio/commit/b9d8c432dd98781b13ab2c502347342193e2fe1b , please check.

**Comment by yurivict** [comment]
You are right about AFMT_FLOAT - it isn't defined, your patch is good.

With include soundcard.h, configure.ac needs to be fixed. It shouldn't say "(linux only)", because at least BSDs, and SunOS also use OSS. It should just allow to enable OSS, and __LINUX_OSS__ should be renamed to __USE_OSS__ or similar.

configure.ac also says "OSS support requires ALSA for RtMidi", which is a bogus requirement, because OSS and ALSA are entirely different, and not related in any way.

**Comment by garyscavone** [comment]
Does the "case $host in” *-*-linux*)” check work for BSDs and SunOS?

Regarding the comment about ALSA being needed for RtMidi, that is a bit confusing. The point is that there is no native support in RtMidi for OSS. And since I assume that if you want to compile realtime support into Stk you probably also want MIDI functionality, then we need to check for the asound library so that RtMidi will correctly compile.

So, the lack of Native OSS support in RtMidi is probably a limitation for BSD and SunOS. I used to support MIDI in OSS but at some point I could no longer test it.

**Comment by yurivict** [comment]
> Does the "case $host in” *-*-linux*)” check work for BSDs and SunOS?

No, I had to add '*-*-freebsd*)' there.

**Pull request closed without merging**
